version: '2'
services:
  configServer:
    image: docker.today36524.com.cn:5000/basic/dapeng-config-server:V2.0
    container_name: configServer
    restart: on-failure:3
    stop_grace_period: 30s
    environment:
      - serviceName=configServer
      - deploy_socket_url=127.0.0.1:6886
      - TZ=CST-8
      - soa_zookeeper_host=127.0.0.1:2181
      - JAVA_OPTS= -Dname=configServer -Xms512M -Xmx512M -Xss256K -Dfile.encoding=UTF-8 -Dsun.jun.encoding=UTF-8
    ports:
      - "6800:8080"
    volumes:
      - "/data/logs/dapeng-config-server/:/usr/local/tomcat/logs"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=