apiVersion: v1
kind: Service
metadata:
  labels:
    app: @SERVICE_NAME@
  name: @SERVICE_NAME@
  namespace: @NAMESPACE@
spec:
  ports:
  - name: @SERVICE_NAME@
    port: @SERVER_PORT@
    protocol: TCP
    targetPort: @CONTAINER_PORT@
    nodePort: @SERVER_PORT@
  selector:
    app: @SERVICE_NAME@
  type: NodePort

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: Reconcile
  name: @SERVICE_NAME@
  namespace: @NAMESPACE@
spec:
  replicas: @REPLICAS@
  selector:
    matchLabels:
      app: @SERVICE_NAME@
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 3
        maxUnavailable: 2
  minReadySeconds: 120

  template:
    metadata:
      labels:
         app: @SERVICE_NAME@
    spec:
      containers:
      - image: @IMAGE@
        name: @SERVICE_NAME@
        volumeMounts:
@VOLUME_MOUNT@
        ports:
        - containerPort: @CONTAINER_PORT@
          protocol: TCP
        env:
@ENVIRONMENTS@
        - name: host_ip
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP

      restartPolicy: Always
      #dnsConfig:
        #nameservers:
          # - @IP@
      volumes:
@VOLUME@

@PVPC_VOLUME@
