apiVersion: v1
kind: Service
metadata:
  labels:
    app: @SERVICE_NAME@
  name: @SERVICE_NAME@
  namespace: @NAMESPACE@
spec:
  ports:
  - name: @SERVICE_NAME@
    port: @PORT@
    protocol: TCP
    targetPort: @PORT@
    nodePort: @PORT@
  selector:
    app: @SERVICE_NAME@
  type: NodePort

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: Reconcile
  name: @SERVICE_NAME@
  namespace: @NAMESPACE@
spec:
  replicas: @REPLICAS@
  selector:
    matchLabels:
      app: @SERVICE_NAME@
  template:
    metadata:
      labels:
         app: @SERVICE_NAME@
    spec:
      containers:
      - image: @IMAGE@
        name: @SERVICE_NAME@
        volumeMounts:
@VOLUME_MOUNT@
        ports:
        - containerPort: @PORT@
          protocol: TCP
        env:
@ENVIRONMENTS@
      restartPolicy: Always
      #dnsConfig:
        #nameservers:
          # - @IP@
      volumes:
@VOLUME@

@PVPC_VOLUME@
