networks:
  sandbox:
    external: {
      name: sandbox
    }
services:
  adminService:
    container_name: adminService
    environment: {
      apm_enable: 'false',
      cas_server_url: 'https://sso.today36524.com',
      container_ip: 10.100.95.50,
      DB_ADMIN_PASSWD: sbpass987654,
      DB_ADMIN_URL: 'jdbc:mysql://10.100.95.50:6033/admin_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect＝true',
      DB_ADMIN_USER: sbuser,
      DB_CATEGORYDB_PASSWD: sbpass987654,
      DB_CATEGORYDB_URL: 'jdbc:mysql://10.100.95.50:6033/category_db?useUnicode=true&autoReconnect＝true',
      DB_CATEGORYDB_USER: sbuser,
      DB_CENTER_STORES_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_CENTER_STORES_URL: 'jdbc:mysql://10.100.95.50:3350/stores_db?useUnicode=true&characterEncoding=utf8',
      DB_CENTER_STORES_USER: dev_user,
      DB_CHECK_ACCOUNT_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_CHECK_ACCOUNT_URL: 'jdbc:mysql://10.100.95.50:3350/check_account_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      DB_CHECK_ACCOUNT_USER: dev_user,
      DB_COMMONDATADB_PASSWD: sbpass987654,
      DB_COMMONDATADB_URL: 'jdbc:mysql://10.100.95.50:6033/common_data_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect＝true',
      DB_COMMONDATADB_USER: sbuser,
      DB_COMMONDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_COMMONDB_URL: 'jdbc:mysql://10.100.95.50:3350/common_db?useUnicode=true&zeroDateTimeBehavior=convertToNull',
      DB_COMMONDB_USER: dev_user,
      DB_DAILYREPORTDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_DAILYREPORTDB_URL: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_DAILYREPORTDB_USER: dev_user,
      DB_FINANCE_CAPITAL_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_FINANCE_CAPITAL_URL: 'jdbc:mysql://10.100.95.50:3350/finance_capital_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      DB_FINANCE_CAPITAL_USER: dev_user,
      DB_FINANCE_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_FINANCE_REPORT_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_FINANCE_REPORT_URL: 'jdbc:mysql://10.100.95.50:3350/finance_report_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      DB_FINANCE_REPORT_USER: dev_user,
      DB_FINANCE_TASK_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_FINANCE_TASK_URL: 'jdbc:mysql://10.100.95.50:3350/finance_task_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      DB_FINANCE_TASK_USER: dev_user,
      DB_FINANCE_URL: 'jdbc:mysql://10.100.95.50:3350/finance?useUnicode=true&failOverReadOnly=false&autoReconnect=true',
      DB_FINANCE_USER: dev_user,
      DB_GOODSDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_GOODSDB_URL: 'jdbc:mysql://10.100.95.50:3350/goods_db?useUnicode=true&zeroDateTimeBehavior=convertToNull',
      DB_GOODSDB_USER: dev_user,
      DB_HIVE_FINANCE_PASSWD: '',
      DB_HIVE_FINANCE_URL: 'jdbc:hive2://192.168.71.127:10000/finance?hive.mapred.mode=nonstrict',
      DB_HIVE_FINANCE_USER: goods,
      DB_HIVE_ORDER_PASSWD: '',
      DB_HIVE_ORDER_URL: 'jdbc:hive2://192.168.71.127:10000/ods?hive.mapred.mode=nonstrict',
      DB_HIVE_ORDER_USER: goods,
      DB_JOURNAL_DATA_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_JOURNAL_DATA_URL: 'jdbc:mysql://10.100.95.50:3350/journal_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull',
      DB_JOURNAL_DATA_USER: dev_user,
      DB_MEMBER_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_MEMBER_PR_PASSWD: sbpass987654,
      DB_MEMBER_PR_USER: sbuser,
      DB_MEMBER_URL: 'jdbc:mysql://10.100.95.50:3350/member?useUnicode=true&characterEncoding=utf8',
      DB_MEMBER_USER: dev_user,
      DB_MEMBE_PR_URL: 'jdbc:mysql://10.100.95.50:6033/member?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect＝true',
      DB_NEWSTOCK_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_NEWSTOCK_URL: 'jdbc:mysql://10.100.95.50:3350/stock_db?useUnicode=true&characterEncoding=utf8',
      DB_NEWSTOCK_USER: dev_user,
      DB_ORDER_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_ORDER_URL: 'jdbc:mysql://10.100.95.50:3350/order_db?useUnicode=true&failOverReadOnly=false&autoReconnect=true',
      DB_ORDER_USER: dev_user,
      DB_OUTWARD_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_OUTWARD_URL: 'jdbc:mysql://10.100.95.50:3350/outward_db?useUnicode=true&failOverReadOnly=false&autoReconnect=true',
      DB_OUTWARD_USER: dev_user,
      DB_PRESTO_FINANCE_PASSWD: '',
      DB_PRESTO_FINANCE_URL: 'jdbc:presto://192.168.71.127:9090/hive/finance',
      DB_PRESTO_FINANCE_USER: goods,
      DB_PRESTO_ORDER_PASSWD: '',
      DB_PRESTO_ORDER_URL: 'jdbc:presto://192.168.71.127:9090/hive/ods',
      DB_PRESTO_ORDER_USER: goods,
      DB_PUBLICKEY: xx,
      DB_PURCHASEDB_PASSWD: sbpass987654,
      DB_PURCHASEDB_URL: 'jdbc:mysql://10.100.95.50:6033/purchase_db?useUnicode=true&failOverReadOnly=false&autoReconnect=true',
      DB_PURCHASEDB_USER: sbuser,
      DB_RECOMMENDDB_PASSWD: today-36524,
      DB_RECOMMENDDB_URL: 'jdbc:mysql://10.100.95.50:3350/recommend_db?useUnicode=true&characterEncoding=utf8',
      DB_RECOMMENDDB_USER: root,
      DB_STOCKDB_PASSWD: today-36524,
      DB_STOCKDB_URL: 'jdbc:mysql://10.100.191.99:3350/stock_db?useUnicode=true&characterEncoding=utf8&failOverReadOnly=false&autoReconnect＝true',
      DB_STOCKDB_USER: root,
      DB_STOCK_PASSWD: sbpass987654,
      DB_STOCK_SUMMARY_PASSWD_0: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_PASSWD_1: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_PASSWD_2: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_PASSWD_3: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_PASSWD_4: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_PASSWD_5: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_PASSWD_6: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_PASSWD_7: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      DB_STOCK_SUMMARY_URL_0: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_URL_1: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_URL_2: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_URL_3: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_URL_4: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_URL_5: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_URL_6: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_URL_7: 'jdbc:mysql://10.100.95.50:3350/daily_statistics_db?useUnicode=true&characterEncoding=utf8',
      DB_STOCK_SUMMARY_USER_0: dev_user,
      DB_STOCK_SUMMARY_USER_1: dev_user,
      DB_STOCK_SUMMARY_USER_2: dev_user,
      DB_STOCK_SUMMARY_USER_3: dev_user,
      DB_STOCK_SUMMARY_USER_4: dev_user,
      DB_STOCK_SUMMARY_USER_5: dev_user,
      DB_STOCK_SUMMARY_USER_6: dev_user,
      DB_STOCK_SUMMARY_USER_7: dev_user,
      DB_STOCK_URL: 'jdbc:mysql://10.100.95.50:6033/stock_db?useUnicode=true&failOverReadOnly=false&autoReconnect=true',
      DB_STOCK_USER: sbuser,
      DB_SUPPLIERDB_PASSWD: sbpass987654,
      DB_SUPPLIERDB_URL: 'jdbc:mysql://10.100.95.50:6033/supplier_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect＝true',
      DB_SUPPLIERDB_USER: sbuser,
      DB_TD_MARKET_PASSWD: today-36524,
      DB_TD_MARKET_URL: 'jdbc:mysql://10.100.95.50:3350/td_market?useUnicode=true&characterEncoding=utf8',
      DB_TD_MARKET_USER: root,
      DB_TD_MINI_PASSWD: today-36524,
      DB_TD_MINI_URL: 'jdbc:mysql://10.100.95.50:3350/td_mini?useUnicode=true&characterEncoding=utf8',
      DB_TD_MINI_USER: root,
      DB_TD_STORE_PASSWD: today-36524,
      DB_TD_STORE_URL: 'jdbc:mysql://10.100.95.50:3350/td_store?useUnicode=true&characterEncoding=utf8',
      DB_TD_STORE_USER: root,
      E_JAVA_OPTS: '-Dname=adminService -Xms256M -Xmx256M -Xss256K -XX:MetaspaceSize=256M
        -XX:MaxMetaspaceSize=256M -Dio.netty.leakDetectionLevel=advanced',
      fluentBitGcInfoPath: /dapeng-container/logs/gc*.log,
      fluentbitGcInfoTag: gcInfoTag,
      fluentBitLogPath: /dapeng-container/logs/*.log,
      fluentBitLogPathExclude: '/dapeng-container/logs/fluent*.log,/dapeng-container/logs/console.log,/dapeng-container/logs/gc*.log',
      fluentbitParserRegex: '(?<logtime>^\d{2}-\d{2} \d{2}:\d{2}:\d{2} \d{3}) (?<threadPool>[^
        ]+|Check idle connection Thread) (?<level>[^ ]+) \[(?<sessionTid>\w*)\] -
        (?<message>.*)',
      fluentbitTag: dapeng,
      fluent_bit_enable: 'false',
      host_ip: 10.100.95.50,
      kafka_consumer_host: '10.100.95.50:9092',
      kafka_producer_host: '10.100.95.50:9092',
      LANG: zh_CN.UTF-8,
      pingying_redis_ip_or_master_name: 10.100.226.227,
      pingying_redis_port_or_sentinels: '8003',
      pinying_redis_host_ip: 10.100.226.227,
      pinying_redis_host_port: '8003',
      pinying_redis_host_timeout: '2000',
      pinying_redis_master_name: master-2,
      pinying_redis_sentinels: '10.100.95.50:27001',
      pinying_redis_type: '1',
      READ_ONLY_DB_CATEGORYDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_CATEGORYDB_URL: 'jdbc:mysql://10.100.95.50:3350/category_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      READ_ONLY_DB_CATEGORYDB_USER: dev_user,
      READ_ONLY_DB_GOODSDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_GOODSDB_URL: 'jdbc:mysql://10.100.95.50:3350/goods_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull',
      READ_ONLY_DB_GOODSDB_USER: dev_user,
      READ_ONLY_DB_MEMBER_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_MEMBER_URL: 'jdbc:mysql://10.100.95.50:3350/member?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      READ_ONLY_DB_MEMBER_USER: dev_user,
      READ_ONLY_DB_ORDERDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_ORDERDB_URL: 'jdbc:mysql://10.100.95.50:3350/order_db?useUnicode=true&failOverReadOnly=false&autoReconnect=true',
      READ_ONLY_DB_ORDERDB_USER: dev_user,
      READ_ONLY_DB_ORDER_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_ORDER_URL: 'jdbc:mysql://10.100.95.50:3350/order_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      READ_ONLY_DB_ORDER_USER: dev_user,
      READ_ONLY_DB_PURCHASEDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_PURCHASEDB_URL: 'jdbc:mysql://10.100.95.50:3350/purchase_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      READ_ONLY_DB_PURCHASEDB_USER: dev_user,
      READ_ONLY_DB_STOCK_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_STOCK_URL: 'jdbc:mysql://10.100.95.50:3350/stock_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      READ_ONLY_DB_STOCK_USER: dev_user,
      READ_ONLY_DB_SUPPLIERDB_PASSWD: GJbeuZBL9rp2Q9lfPinakTw6awBc70,
      READ_ONLY_DB_SUPPLIERDB_URL: 'jdbc:mysql://10.100.95.50:3350/supplier_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true',
      READ_ONLY_DB_SUPPLIERDB_USER: dev_user,
      redis_host_ip: 10.100.226.227,
      redis_host_port: '8002',
      redis_host_timeout: '2000',
      redis_ip_or_master_name: 10.100.226.227,
      redis_master_name: master-1,
      redis_port_or_sentinels: '8002',
      redis_sentinels: '10.100.95.50:27001',
      redis_type: '1',
      serviceName: adminService,
      slow_service_check_enable: 'true',
      soa_container_ip: 10.100.95.50,
      soa_container_port: '9083',
      soa_core_pool_size: '100',
      soa_freq_limit_enable: 'false',
      soa_freq_shm_data: /data/shm/shm.data,
      soa_jmxrmi_enable: 'false',
      soa_monitor_enable: 'false',
      soa_service_timeout: '10000',
      soa_transactional_enable: 'false',
      soa_zookeeper_host: '10.100.95.50:2181',
      TZ: CST-8
    }
    extra_hosts: [
      'sandbox-1:10.100.95.50']
    image: harbor.today36524.td/biz/admin_service:latest
    labels: [
      'project.source=http://pms.today36524.td/central-services/admin.git@@adminService;sbt
        clean api/publishLocal api/publishM2 docker',
      'project.depends=mysql,zookeeper,idGenService',
      project.owner=XUSHENG]
    networks: [
      sandbox]
    ports: [
      '9083:9083']
    restart: on-failure:3
    stop_grace_period: 30s
    volumes: [
      '/data/logs/dapeng/admin-service:/dapeng-container/logs',
      '/data/var/fluent/adminService:/fluent-bit/db',
      '/data/var/shm:/data/shm']
    
version: '2'
