apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: Reconcile
  name: @SERVICE_NAME@
  namespace: @NAMESPACE@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @SERVICE_NAME@
  template:
    metadata:
      labels:
         app: @SERVICE_NAME@
    spec:
      containers:
      - image: @IMAGE@
        name: @SERVICE_NAME@
        volumeMounts:
@VOLUME_MOUNT@
        ports:
        - containerPort: @PORT@
          protocol: TCP
        env:
@ENVIRONMENTS@
      restartPolicy: Always
      #dnsConfig:
        #nameservers:
          # - @IP@
      volumes:
@VOLUME@

---
